### ISSUE TITLE
Проблемы с jsx-one-expression-per-line

### ISSUE THREAD

**Issue by NatalyaZ** [alfa-laboratory/arui-presets-lint#109]
После форматирования некоторый код выглядит очень громоздко
Было
```
<Typography.Text weight="bold">
    Платёж <Amount.Pure amount={ payment } /> спишем { data }
</Typography.Text>
```
Стало
```
<Typography.Text weight="bold">
    Платёж
    { ' ' }
    <Amount.Pure amount={ payment } />
    { ' ' }
    спишем
    { ' ' }
    { data }
</Typography.Text>
```
Можно отключать этот параметр или отменить?

Был [ПР](https://github.com/alfa-laboratory/arui-presets-lint/pull/17) по отключению, почему вернули правило?

**Comment by MadBrozzeR** [comment]
Присоединяюсь. Компоненты с этим правилом выглядят ужасно. В своём проекте приходится в каждом файле правило отключать.

**Comment by MadBrozzeR** [comment]
Из очередных зацепок я прихожу к выводу, что специально правило никто не убирал, оно просто куда-то потерялось.
Здесь оно было убрано из общих правил, так как содержится в подключаемом `prettier/react`:
https://github.com/alfa-laboratory/arui-presets-lint/commit/921947d250aa8c95f0709d001a6dd0dff21cf6c3#diff-e420729b35e103f76fa3f056ad824553259edcc63ece848391c3f89a29914c2dL51

а в данный момент почему-то этого подключаемого набора нет. Нужно разобраться, куда и почему оно делось.
