### ISSUE TITLE
Улучшение для eslint

### ISSUE THREAD

**Issue by etroynov** [alfa-laboratory/arui-presets-lint#20]
Предлагаю внести следующие изменения в eslint.js :
- перейти на @typescript-eslint/parser ( т.к во многих проектах tslint нету и линтинг должен выполнятся средствами eslint ;
- перейти с eslint-config-airbnb на  eslint-config-airbnb-base;
- убрать в конце концов TODO ;
- рассмотреть вынос некоторых правил и настроек в локальные конфиги ( например chai );
- sort class members очень спорная вещь возможно стоит пересмотреть;

**Comment by Luchanso** [comment]
1. В arui-preset-lint нету `@typescript-eslint/parser`. Tslint нужен в arui-presets-ts
2. В eslint-config-airbnb-base отличие же только в том, что не описаны правила для реакта?
3. Было бы здорово убрать все TODO, кто хочет в этом помочь?)
4. Да, chai идёт, как плагин поэтому эта хорошая идея
5. Какие вещи в sort class members хочется поменять? Я бы оставил как есть, не потому что мне нравится, а потому что ты правильно заметил - будет много споров)

**Comment by etroynov** [comment]
> 1. В arui-preset-lint нету @typescript-eslint/parser. Tslint нужен в arui-presets-ts;

Я знаю но tslint deprecated:
https://github.com/palantir/tslint

поэтому от него нужно отказываться, к тому же есть офиц плагин для безболезненного перехода с ESLint -> TSLint.

**Comment by etroynov** [comment]
> 2. eslint-config-airbnb-base отличие же только в том, что не описаны правила для реакта;

Не только, он рекомендуется для построения своих конфигов, а это как раз наш случай.

**Comment by etroynov** [comment]
> 5. Какие вещи в sort class members хочется поменять? Я бы оставил как есть, не потому что мне нравится, а потому что ты правильно заметил - будет много споров)

Как раз таки и смущает тот факт что это не официальная рекомендация и не общепринятый подход ( по крайней мере я не нашел никакой информации по этому поводу ), а чей то личный выбор на основе его предпочтений.

**Comment by Heymdall** [comment]
Собсно считаю что большу часть из этого закрыли в #15
