### ISSUE TITLE
WARNING: Module not found: arui-feather/*.css

### ISSUE THREAD

**Issue by reme3d2y** [alfa-laboratory/arui-presets-lint#24]
Получаю ворнинги при подключении линтеров на [https://github.com/alfa-laboratory/core-components](url).

Во время запуска `stylelint ./packages/**/*.css` выводятся следующие сообщения:
```
WARNING: Module not found: arui-feather/vars.css
WARNING: Module not found: arui-feather/vars/font.css
WARNING: Module not found: arui-feather/vars/opacity.css
WARNING: Module not found: arui-feather/vars/primitive-colors.css
```

Ворнинги идут из [arui-cssvars](https://github.com/MadBrozzeR/arui-cssvars/blob/e37618eac9b9c5686f9e3fdc194085e5a4f2bd4d/utils.js#L33). Скрипт пытается найти эти файлы в `arui-feather`, который не используется в `core-components`.

Я что-то делаю не так?

**Comment by Luchanso** [comment]
@MadBrozzeR

**Comment by MadBrozzeR** [comment]
Можно попробовать заоверрайдить правило в stylelint конфиге:
https://github.com/alfa-laboratory/core-components/blob/master/stylelint.config.js
```
    rules: {
        ...
        'arui-cssvars/use-variables': false,
```

**Comment by stepancar** [comment]
@MadBrozzeR есть какой-то прогресс?

**Comment by MadBrozzeR** [comment]
@stepancar Не занимался, так как на работу не влияет. Но вообще, фикс не должен быть сложным. Постараюсь на этой неделе починить.

**Comment by MadBrozzeR** [comment]
@reme3d2y @stepancar Поправлено в 4.1.1. Необходимо в проекте отключить линтовое правило в package.json
```
    rules: {
        ...
        'arui-cssvars/use-variables': false,
```

**Comment by reme3d2y** [comment]
Обновился - теперь все ок 👍
