### ISSUE TITLE
Нельзя записывать изменять значение memo в reduce

### ISSUE THREAD

**Issue by prosto-lapsha** [alfa-laboratory/arui-presets-lint#25]
В reduce нельзя перезаписывать результат
![image](https://user-images.githubusercontent.com/18405099/77074251-9f661380-6a01-11ea-9b4b-20fd6a21bec2.png)

**Comment by Heymdall** [comment]
Не отклоняемся от airbnb.
https://github.com/airbnb/javascript#functions--mutate-params
Правильным в данном случае будет
```
const foo = Object.keys(bar).reduce((prev, serviceName) => {
    return {
        ...prev,
        [serviceName]: 'тра-та-та-тата'
    };
})
```

**Comment by aweppc** [comment]
е бои, больше объектов в памяти

**Comment by Heymdall** [comment]
Хм. Хотел сказать сначала что все фигня и разница поп производительности будет минимальна. Но вот есть хороший issue на эту тему. https://github.com/airbnb/javascript/issues/719
По сути можно попробовать втащить нам https://github.com/Pustur/edabit-js-challenges/commit/e40aed964285ab186b843d387e484d59c240f8ad
Вот такое решение
Действительно, кажется разница в перфомансе получается значительной

**Comment by reme3d2y** [comment]
Кодстайл это конечно очень важно, но не когда на пустом месте теряется производительность. 
На рабочих маках все летает, но у пользователей совсем другие устройства 🤷‍♂️

Я бы вынес это правило на голосование

**Comment by Heymdall** [comment]
Так про что голосовать то будем? 
Кажется что действительно надо правило поменять. Возможное решение я привел. Полностью выключать его не хочется, так как кейсы когда параметры перетираются чем то еще - все же как правило не желательны

**Comment by aweppc** [comment]
Я бы вариант pustur всунул и всё. Пока что.

На будущее запилить бы формочку, в которой собирать лайки/дизлайки к конкретным правилам, а потом раз в n времени пересматривать эти линты, чтобы не подрываться всеми фронтами обновлять проекты раз в неделю

**Comment by reme3d2y** [comment]
Там в треде предложили вариант с исключением reduce:
https://github.com/mathieudutour/eslint-plugin-no-not-accumulator-reassign

Это правило действительно очень полезное и полностью отключать его не стоит, но в случае с reduce (и возможно в некоторых других кейсах) - оно делает код хуже.

**Comment by 7rulnik** [comment]
Медленнее не значит медленно. Даже если в десятки раз. Да, есть аллокация, но есть и GC. Коллекции обычно не очень большие, чтобы даже на дохлых девайсах как-то влиять на перфоманс. Более того, если перфоманс кажется важным и потери неприемлемы, то и сам редьюс особо не нужен и можно всё сделать через  for/of или forEach. А если всё таки хочется редьюс и мутацию, то можно выключить правило локально.

**Comment by Heymdall** [comment]
Нуу. В целом я с тобой согласен. Но кейс с reduce - очень частый. И он реально сильно бьет по производительности.

```var array = Array.from(Array(10000).keys()); 

// Spread operator (same with Object.assign)
var t0 = performance.now();
array.reduce((acc, number) => ({ ...acc, [number]: null }), {});
var t1 = performance.now();
console.log(t1 - t0); // 82.86500000394881

// Mutating the accumulator
t0 = performance.now();
array.reduce((acc, number) => { acc[number] = null; return acc }, {});
t1 = performance.now();
console.log(t1 - t0); // 0.4950000438839197
```
Да, в абсолютных числах - разница не велика. Но в относительных разница даже не в десятки, а в сотню раз.
И как правильно заметили в том же issue в airbnb - в данном случае у разработчика остается либо вариант написать disable комент, либо писать что-то вроде 
```
let acc = {}
array.forEach()
```
что скорее только ухудшает читабельность всего этого. Поэтому на мой взгляд профит от правила в целом - понятен, а вот от частного случая - скорее понятен вред.

**Comment by reme3d2y** [comment]
Использование `acc` и `accumulator` не вызывает ошибку. 

[https://github.com/airbnb/javascript/blob/master/packages/eslint-config-airbnb-base/rules/best-practices.js#L192](url)


![image](https://user-images.githubusercontent.com/9968618/77141654-b7d03f80-6a8e-11ea-854b-feeb6468376b.png)

![image](https://user-images.githubusercontent.com/9968618/77141599-8c4d5500-6a8e-11ea-8b07-d209f9a4fa0d.png)

**Comment by 7rulnik** [comment]
О, забавно. Не знал. Ну вот кажется и решение?

**Comment by reme3d2y** [comment]
Да, можно все оставить как есть

**Comment by penartur** [comment]
> Да, в абсолютных числах - разница не велика. Но в относительных разница даже не в десятки, а в сотню раз.

Так важна разница как раз в абсолютных значениях.
Если пользователь нажимает на кнопку и ждёт реакции приложения секунду, то нет разницы, оптимизируем мы какой-то занимающий из этой секунды 10 микросекунд кусок в сто раз, или нет.

Поддержу @7rulnik, если замедление работы reduce в сто раз начинает влиять на пользовательские ощущения, то проблема не в замедлении работы reduce.



> Правильным в данном случае будет
> 
> ```
> const foo = Object.keys(bar).reduce((prev, serviceName) => {
>     return {
>         ...prev,
>         [serviceName]: 'тра-та-та-тата'
>     };
> })
> ```

Ещё зачастую можно воспользоваться lodash. Например, весь исходный пример можно было бы записать как
```
import mapValues from 'lodash.mapvalues';

...
services: mapValues(SERVICES, (service) => {
    const versionString = USE_VERSIONS ? `-v${service.version}` : '';

    return {
        healthCheck: `/${PROJECT_NAME}-${service.name}${versionString}/admin/health`
    };
});
```

И сразу и линтер удовлетворён, и код стал короче и понятнее (но ценой зависимости от lodash.mapValues).

**Comment by reme3d2y** [comment]
@penartur конкретно в этом кейсе с reduce - вообще не согласен.
Осознано ухудшать производительность только ради того, чтобы линтер не ругался - это странный подход.
Да, в целом правило правильное, но всегда есть исключения. И благо в линтер его добавили.
