### ISSUE TITLE
Неточность в README.md

### ISSUE THREAD

**Issue by reme3d2y** [alfa-laboratory/arui-presets-lint#26]
В `package.json` должно быть так:

```
"lint-staged": {
  "src/**/*.{js,jsx,ts,tsx}": [
    "prettier --write",
     "git add",
     "eslint"
  ],
  "*.css": [
    "prettier --write",
    "git add",
    "stylelint"
  ]
},
```

**Comment by prosto-lapsha** [comment]
у меня с конфигурацией из текущего Readme вот такие ошибки падают на прекоммите
![image](https://user-images.githubusercontent.com/18405099/77148795-4ea5f780-6aa1-11ea-92a4-dea0df6320f0.png)

**Comment by reme3d2y** [comment]
У меня было так же. Решил так, как в пред. сообщении
