### ISSUE TITLE
Убрать из линтера правило react/no-did-update-set-state

### ISSUE THREAD

**Issue by zorgick** [alfa-laboratory/arui-presets-lint#28]
**CWRP умер, да здравствует CDUP**

Поскольку CWRP уже устаревший метод и использование его в проекте не рекомендовано, вызывать setState остается только CDUP хуке для доступа к предыдущим пропсам. 

На эту тему уже воют с airbnb на гитхабе https://github.com/airbnb/javascript/issues/1875

К тому же [реактовцы сами разрешают](https://reactjs.org/docs/react-component.html#componentdidupdate) использовать setState в CDUP, если есть условие его выполнения.

**Comment by Heymdall** [comment]
Вообще полностью выключать это правило таки не хочется. Все равно есть возможность что кто-то накосячит и получится бесконечный цикл. Что если перевести это в варнинг? Если же захочется избавиться и от варнингов - можно будет использовать локальный disable коммент.

Таким образом можно все же известить разработчика о том что это потенциально опасный момент, а он сможет отметить "да, я все понимаю, я знаю что я делаю"

**Comment by zorgick** [comment]
можно и в варнинг, реакт изменился поэтому это правило будет так или иначе обходится разрабами с помощью комментов, нивелируя до нуля его полезность
