### ISSUE TITLE
Как писать npm scripts

### ISSUE THREAD

**Issue by stepancar** [alfa-laboratory/arui-presets-lint#34]
```
"script": {
    "lint-css": "stylelint ./src/**/*.css",
    "lint-scripts": "eslint ./src/ ./config/ --ext .js,.jsx,.ts,.tsx",
    "lint": "yarn run lint-css && yarn run lint-scripts",
    "format": "prettier --write \"./{config,src}/**/*.{ts,tsx,js,jsx,css}\""
  },
```

В README вот так и завтра это будет растащено по всем проектам как есть
У @etroynov были комменты по поводу стиля написания скриптов. Он говорил что есть стандарт писать через :
Жень, подискутируй пока не поздно

**Comment by 7rulnik** [comment]
Да, очень часто разделяют через `:`. Например `lint`, `lint:css`, `lint:js`.

**Comment by etroynov** [comment]
да еще с bash повелось что ```:``` используют как своего рода namespace для команд, поэтому так очень часто делают это негласный стандарт.

Как такового как писать команды в скриптах, стандарта нету.

**Comment by stepancar** [comment]
@Heymdall че думаешь?

**Comment by Heymdall** [comment]
Согласен. Не трогал эту часть ридми, действительно разумно использовать более или менее общепринятый стандарт
