### ISSUE TITLE
eslint: лишние зависемости 

### ISSUE THREAD

**Issue by etroynov** [alfa-laboratory/arui-presets-lint#36]
Линтер просит перенести зависимости необходимые для разработки в dependencies хотя они должны быть в devDependencies:

<img width="1025" alt="Screenshot 2020-03-22 at 20 21 23" src="https://user-images.githubusercontent.com/4591518/77255747-d6932980-6c7a-11ea-831c-5ac44017e688.png">

**Comment by stepancar** [comment]
@etroynov так он ниче не знает про стори и что они там же где и сорцы лежат. Надо для сторей просто правило подправить

**Comment by Heymdall** [comment]
Какой стандартный паттерн наименований для сторибука? `*.stories.ts`

**Comment by stepancar** [comment]
*.stories.tsx?

@Heymdall

**Comment by Heymdall** [comment]
Поправлено в `4.1.0`
