### ISSUE TITLE
Некорректная работа правила react/button-has-type

### ISSUE THREAD

**Issue by reme3d2y** [alfa-laboratory/arui-presets-lint#38]
Данное правило не позволяет задавать аттрибут `type` динамически.

```
export const Button: React.FC<{
    type?: 'button' | 'reset' | 'submit';
}> = ({ type = 'button' }) => {
    return <button type={type}>Кнопка</button>;
};
```

Этот код дает вот такую ошибку:
`type` is an invalid value for button type attribute
**eslint(react/button-has-type)**

[Обсуждение правила](https://github.com/yannickcr/eslint-plugin-react/issues/1555)

**Comment by Heymdall** [comment]
Кажется, подобные штуки лучше всего решать через disable коменты. Само по себе правила зла не несет, но реализация у него действительно хромает. Тем не менее, в общем случае, правило хорошее.
