### ISSUE TITLE
Добавить cypress в Readme

### ISSUE THREAD

**Issue by IH8E** [alfa-laboratory/arui-presets-lint#39]
Сейчас cypress аналогично директориям config и src есть во многих проектах.
Кажется исходя из этого есть смысл:
1. Обновить строчку в Readme с командой `format` и добавить cypress
2. Добавить cypress в команду `lint-scripts`, правда для этого нужно будет обновлять конфиг eslint'а

**Comment by stepancar** [comment]
@Heymdall @ilatovsky @aweppc @Luchanso @samoxbal У нас cypress является же вроде стандартом. Добавим сразу и в правила и в ридми чтоб поминимум напрягать людей с настройкой?

**Comment by Heymdall** [comment]
Про ридми понял, про правила - не совсем. Про https://github.com/cypress-io/eslint-plugin-cypress - вот это речь?

**Comment by IH8E** [comment]
@Heymdall да, там как минимум нужно будет добавить `cy` в `globals`, а лучше использовать этот плагин.

**Comment by Luchanso** [comment]
Поддерживаю, давайте просто добавим этот плагин
