### ISSUE TITLE
Перестали работать правила eslint которые были раньше

### ISSUE THREAD

**Issue by praiz** [alfa-laboratory/arui-presets-lint#43]
Проблема в том что у prettier свои правила для форматирования кода.

Предлагаю использовать `prettier-eslint` https://github.com/prettier/prettier-eslint чтобы можно было настроить правила под наши стандарты.

**Comment by stepancar** [comment]
@praiz тащи PR, плиз. Так никто ниче не скажет

**Comment by 7rulnik** [comment]
@stepancar @praiz закрываю. Сделано в #44
