### ISSUE TITLE
Конфиг в примере не вызывает команду test

### ISSUE THREAD

**Issue by stepancar** [alfa-laboratory/arui-presets-lint#54]
Я рассматриваю конфиг в ридми как готовый для скопировать вставить как есть. Сейчас там на прекоммите нет запуска тестов

**Comment by voronin-ivan** [comment]
Мне кажется, что не стоит в рамках репы про линтер что-то добавлять про тесты. У нас есть как юниты, так и е2е, причем с различной спецификой, вроде запуска юнитов в ЕФ исключительно командой npm run karma из-за хардкода в пайплайне
