### ISSUE TITLE
Добавить возможность использовать `a && b()`

### ISSUE THREAD

**Issue by FenkoAlex** [alfa-laboratory/arui-presets-lint#65]
Линтер не дает пользоваться короткими выражениями 
Хочу выставить правило 
`no-unused-expressions: ["error", { "allowShortCircuit": true, "allowTernary": true }]`
ну или хоть так
`no-unused-expressions: ["error", { "allowShortCircuit": true }]` 
## Актуальное поведение
```
if (a) {
  b()
}
```
## Ожидаемое поведение
`a && b()`

**Comment by Heymdall** [comment]
На мой взгляд подобные сокращения ухудшают читабельность. 
```
// На мой взгляд при быстром чтении это хуже воспринимается
state.enabled && onClick();

// а это лучше.
if (state.enabled) {
    onClick();
}
```
Особенно если у нас используются более сложные объекты или банально более длинные названия переменных.
Основной поинт любого правила - улучшение читабельности.
Написать `if` не так уж и долго.
Если же проверка ведется самой функции (тип `onClick && onClick()`) - есть optional chaining.
