### ISSUE TITLE
Нехватает @typescript-eslint/no-useless-constructor

### ISSUE THREAD

**Issue by aweppc** [alfa-laboratory/arui-presets-lint#68]
`@typescript-eslint/no-useless-constructor` - правило, расширяющее правило `no-useless-constructor`
Документация на него [вот тут](https://github.com/typescript-eslint/typescript-eslint/blob/master/packages/eslint-plugin/docs/rules/no-useless-constructor.md)
Тайпскриптовая версия правила добавляет поддержку трёх кейсов, один из которых постоянно бьёт мне граблями в лицо - пустой конструктор с объявлением полей

## Пример кода

```
public class Foo {
  // здесь объявляется поле someField, которому присваивается значение одноимённого аргумента,
  // позволяя не объявлять его в классе и не присваивать ему значение в конструкторе
  public constructor(private someField: string) { }
}
```

## Актуальное поведение

В случае из примера выше будет ошибка `Useless constructor. (eslintno-useless-constructor)`

## Ожидаемое поведение

Ошибки тут нет. Здесь объявляется поле класса с присвоением ему значения из аргумента конструктора

**Comment by Heymdall** [comment]
Не актуально. В текущем мастере работает как ожидается. Возможно, необходимо обновить не только версию библиотеки, но и ее зависимости. `npx install-peerdeps --dev arui-presets-lint@5.3.1`
