### ISSUE TITLE
Нехватает @eslint-typescript/no-unused-expressions

### ISSUE THREAD

**Issue by aweppc** [alfa-laboratory/arui-presets-lint#69]
`@eslint-typescript/no-unused-expressions` правило, расширяющее правило no-unused-expressions
Документация на него [вот тут](https://github.com/typescript-eslint/typescript-eslint/blob/master/packages/eslint-plugin/docs/rules/no-unused-expressions.md)
Тайпскриптовая версия правила добавляет поддержку кейса с `null-propagation`, то есть для вызовов вида `x?.method()`

## Пример кода

```
this.logger?.log('здарова');
```

## Актуальное поведение

В случае из примера выше будет ошибка `Expected an assignment or function call and instead saw an expression. (eslintno-unused-expressions)`

## Ожидаемое поведение

Ошибки тут нет. Здесь вызывается метод поля logger, если это поле не undefined или null, а иначе не вызывается

**Comment by Heymdall** [comment]
Не актуально. Работает корректно в текущем мастере. Возможно требуется обновить пакет и его зависимости. `npx install-peerdeps --dev arui-presets-lint@5.3.1`
