### ISSUE TITLE
Environment key "cypress/globals" is unknown

### ISSUE THREAD

**Issue by etroynov** [alfa-laboratory/arui-presets-lint#76]
Появилась ошибка
```
package.json » ./node_modules/arui-presets-lint/eslint/index.js#overrides[1]:
10:44:53 	Environment key "cypress/globals" is unknown
```

**Comment by Heymdall** [comment]
а `eslint-plugin-cypress` стоит в проекте?
он помечен как peer у пресетов. Скорее всего ошибка связана с ним.

Чтобы порешать это концептуально правильно на уровне этого проекта - надо будет пробовать обновиться на eslint7, потому что в нем поменяли работу с плагинами,и, возможно, получится сделать так чтобы плагины были не peer зависимостями

**Comment by etroynov** [comment]
У нас есть проекты:
http://git.moscow.alfaintra.net/projects/NEWCLICK/repos/newclick-composite-components/browse
http://git.moscow.alfaintra.net/projects/NEWCLICK/repos/newclick-components/browse

и т.д, которые не используют cypress.

Наш конфиг не совместим с 7 версией:
```
/Users/etroynov/www/newclick-user-profile-ui/src/server/api/index.ts
  1:1  error  Definition for rule '@typescript-eslint/class-name-casing' was not found  @typescript-eslint/class-name-casing

/Users/etroynov/www/newclick-user-profile-ui/src/server/index.ts
  1:1  error  Definition for rule '@typescript-eslint/class-name-casing' was not found  @typescript-eslint/class-name-casing

/Users/etroynov/www/newclick-user-profile-ui/src/server/mock.ts
  1:1   error    Definition for rule '@typescript-eslint/class-name-casing' was not found  @typescript-eslint/class-name-casing
  8:25  warning  Missing return type on function                                           @typescript-eslint/explicit-module-boundary-types

/Users/etroynov/www/newclick-user-profile-ui/src/server/mock/customer.ts
  1:1  error  Definition for rule '@typescript-eslint/class-name-casing' was not found  @typescript-eslint/class-name-casing

/Users/etroynov/www/newclick-user-profile-ui/src/server/plugins/api/customerInfo.ts
  1:1  error  Definition for rule '@typescript-eslint/class-name-casing' was not found  @typescript-eslint/class-name-casing

/Users/etroynov/www/newclick-user-profile-ui/src/server/plugins/index.ts
  1:1   error    Definition for rule '@typescript-eslint/class-name-casing' was not found  @typescript-eslint/class-name-casing
  9:27  warning  Missing return type on function                                           @typescript-eslint/explicit-module-boundary-types

/Users/etroynov/www/newclick-user-profile-ui/src/server/server.ts
  1:1  error  Definition for rule '@typescript-eslint/class-name-casing' was not found  @typescript-eslint/class-name-casing

/Users/etroynov/www/newclick-user-profile-ui/src/typings/config.ts
  1:1  error  Definition for rule '@typescript-eslint/class-name-casing' was not found  @typescript-eslint/class-name-casing

/Users/etroynov/www/newclick-user-profile-ui/src/typings/global.d.ts
   1:1  error  Definition for rule '@typescript-eslint/class-name-casing' was not found      @typescript-eslint/class-name-casing
  15:5  error  Definition for rule '@typescript-eslint/interface-name-prefix' was not found  @typescript-eslint/interface-name-prefix

/Users/etroynov/www/newclick-user-profile-ui/src/typings/modules.d.ts
  1:1  error  Definition for rule '@typescript-eslint/class-name-casing' was not found  @typescript-eslint/class-name-casing

/Users/etroynov/www/newclick-user-profile-ui/src/utils/email-regexp.ts
  1:1  error  Definition for rule '@typescript-eslint/class-name-casing' was not found  @typescript-eslint/class-name-casing

✖ 68 problems (45 errors, 23 warnings)

error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by Heymdall** [comment]
Тэкс, видимо криво выразился. Смотри. В твоем проекте чтоб все заработало - надо поставить eslint-plugin-cypress. Он есть в peerDependencies  arui-presets-lint. Без него работать не будет. То что на проекте при этом нет cypress - не важно. 
Для того, чтоб в последствии можно было избежать таких проблем - arui-presets-lint нужно обновить на 7 eslint. Это большая и жирная задача, которую нужно делать отдельно

**Comment by etroynov** [comment]
> Тэкс, видимо криво выразился. Смотри. В твоем проекте чтоб все заработало - надо поставить eslint-plugin-cypress. Он есть в peerDependencies arui-presets-lint. Без него работать не будет. То что на проекте при этом нет cypress - не важно.
> Для того, чтоб в последствии можно было избежать таких проблем - arui-presets-lint нужно обновить на 7 eslint. Это большая и жирная задача, которую нужно делать отдельно

а зачем тогда в линтер добавили пакет который есть не у всех и который ломает линтер?

**Comment by voronin-ivan** [comment]
@etroynov, ещё актуально с учётом новой мажорки?

**Comment by rd9911** [comment]
Я понимаю, что пишу очень поздно но будущим юзерам со схожей проблемой:
внутри файла .eslintrc.js, добавьте к module.exports = {... ,  'extends': [ ... , 'plugin: cypress/recommended'  ]}. [Линк](https://stackoverflow.com/a/63437384/14772681) на оригинальный ответ.
