### ISSUE TITLE
Не обновляется package.json при релизе

### ISSUE THREAD

**Issue by Heymdall** [alfa-laboratory/arui-presets-lint#98]
При выпуске новой версии в мастер не попадает обновленный package.json.

Это [известная особенность semantic-release](https://semantic-release.gitbook.io/semantic-release/support/faq#why-is-the-package-jsons-version-not-updated-in-my-repository), и у них есть инструкция как это пофиксить. Было бы приятно иметь в мастере актуальную версию в package.json

**Comment by IBelyaev** [comment]
взял на себя, но пока занимаюсь другой задачей. Если есть желающие - то берите, я ток за.
