### ISSUE TITLE
Сделать multiline-comment-style = separate-lines

### ISSUE THREAD

**Issue by denisx** [alfa-laboratory/arui-presets-lint#99]
При комменте куска кода, линтеру не нравиться такое

<img width="300" alt="Screenshot 2020-09-30 at 09 45 18" src="https://user-images.githubusercontent.com/427776/94651837-bc10cb80-0301-11eb-88ab-1cd7a590b0a1.png">

и ему подавай вот такое

<img width="194" alt="Screenshot 2020-09-30 at 09 45 28" src="https://user-images.githubusercontent.com/427776/94651847-c29f4300-0301-11eb-9c02-4619c0c6465a.png">

## Мотивация изменений

некомфортно при разработке и не коммит-френдли

**Comment by praiz** [comment]
это правило уже офнули https://github.com/alfa-laboratory/arui-presets-lint/commit/65ea774

**Comment by denisx** [comment]
@praiz я не вижу в мастере

**Comment by Heymdall** [comment]
В текущем мастере это правило вообще не описано, оно берется из базового набора airbnb. https://github.com/airbnb/javascript/blob/master/packages/eslint-config-airbnb-base/rules/style.js#L245 и там оно выключено.
Так же проверил в текущем мастере, коменты не энфорсятся.
